[package]
name = "transpire"
version = "0.1.0"
authors = ["Orhan Yigit Yazicilar <oyy1@st-andrews.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
argparse = "0.2.2"
=======
regex = "1"
>>>>>>> 7843c4b3f3916bb4b1b56d84a714f8a75887d53b
